/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <stdint.h>
#include <stdlib.h>
#include <lcm/lcm_coretypes.h>
#include <lcm/lcm.h>

#ifndef _lcmt_servotubeState_h
#define _lcmt_servotubeState_h

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _lcmt_servotubeState lcmt_servotubeState;
struct _lcmt_servotubeState
{
    int64_t    timestamp;
    double     position;
    double     positionSecondary;
};
 
lcmt_servotubeState   *lcmt_servotubeState_copy(const lcmt_servotubeState *p);
void lcmt_servotubeState_destroy(lcmt_servotubeState *p);

typedef struct _lcmt_servotubeState_subscription_t lcmt_servotubeState_subscription_t;
typedef void(*lcmt_servotubeState_handler_t)(const lcm_recv_buf_t *rbuf, 
             const char *channel, const lcmt_servotubeState *msg, void *user);

int lcmt_servotubeState_publish(lcm_t *lcm, const char *channel, const lcmt_servotubeState *p);
lcmt_servotubeState_subscription_t* lcmt_servotubeState_subscribe(lcm_t *lcm, const char *channel, lcmt_servotubeState_handler_t f, void *userdata);
int lcmt_servotubeState_unsubscribe(lcm_t *lcm, lcmt_servotubeState_subscription_t* hid);

int  lcmt_servotubeState_encode(void *buf, int offset, int maxlen, const lcmt_servotubeState *p);
int  lcmt_servotubeState_decode(const void *buf, int offset, int maxlen, lcmt_servotubeState *p);
int  lcmt_servotubeState_decode_cleanup(lcmt_servotubeState *p);
int  lcmt_servotubeState_encoded_size(const lcmt_servotubeState *p);

// LCM support functions. Users should not call these
int64_t __lcmt_servotubeState_get_hash(void);
int64_t __lcmt_servotubeState_hash_recursive(const __lcm_hash_ptr *p);
int     __lcmt_servotubeState_encode_array(void *buf, int offset, int maxlen, const lcmt_servotubeState *p, int elements);
int     __lcmt_servotubeState_decode_array(const void *buf, int offset, int maxlen, lcmt_servotubeState *p, int elements);
int     __lcmt_servotubeState_decode_array_cleanup(lcmt_servotubeState *p, int elements);
int     __lcmt_servotubeState_encoded_array_size(const lcmt_servotubeState *p, int elements);
int     __lcmt_servotubeState_clone_array(const lcmt_servotubeState *p, lcmt_servotubeState *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
