/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <stdint.h>
#include <stdlib.h>
#include <lcm/lcm_coretypes.h>
#include <lcm/lcm.h>

#ifndef _lcmt_servotubeCommand_h
#define _lcmt_servotubeCommand_h

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _lcmt_servotubeCommand lcmt_servotubeCommand;
struct _lcmt_servotubeCommand
{
    int64_t    timestamp;
    double     commandValue;
    int32_t    commandType;
};
 
lcmt_servotubeCommand   *lcmt_servotubeCommand_copy(const lcmt_servotubeCommand *p);
void lcmt_servotubeCommand_destroy(lcmt_servotubeCommand *p);

typedef struct _lcmt_servotubeCommand_subscription_t lcmt_servotubeCommand_subscription_t;
typedef void(*lcmt_servotubeCommand_handler_t)(const lcm_recv_buf_t *rbuf, 
             const char *channel, const lcmt_servotubeCommand *msg, void *user);

int lcmt_servotubeCommand_publish(lcm_t *lcm, const char *channel, const lcmt_servotubeCommand *p);
lcmt_servotubeCommand_subscription_t* lcmt_servotubeCommand_subscribe(lcm_t *lcm, const char *channel, lcmt_servotubeCommand_handler_t f, void *userdata);
int lcmt_servotubeCommand_unsubscribe(lcm_t *lcm, lcmt_servotubeCommand_subscription_t* hid);

int  lcmt_servotubeCommand_encode(void *buf, int offset, int maxlen, const lcmt_servotubeCommand *p);
int  lcmt_servotubeCommand_decode(const void *buf, int offset, int maxlen, lcmt_servotubeCommand *p);
int  lcmt_servotubeCommand_decode_cleanup(lcmt_servotubeCommand *p);
int  lcmt_servotubeCommand_encoded_size(const lcmt_servotubeCommand *p);

// LCM support functions. Users should not call these
int64_t __lcmt_servotubeCommand_get_hash(void);
int64_t __lcmt_servotubeCommand_hash_recursive(const __lcm_hash_ptr *p);
int     __lcmt_servotubeCommand_encode_array(void *buf, int offset, int maxlen, const lcmt_servotubeCommand *p, int elements);
int     __lcmt_servotubeCommand_decode_array(const void *buf, int offset, int maxlen, lcmt_servotubeCommand *p, int elements);
int     __lcmt_servotubeCommand_decode_array_cleanup(lcmt_servotubeCommand *p, int elements);
int     __lcmt_servotubeCommand_encoded_array_size(const lcmt_servotubeCommand *p, int elements);
int     __lcmt_servotubeCommand_clone_array(const lcmt_servotubeCommand *p, lcmt_servotubeCommand *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
